- repository: autowarefoundation/sync-file-templates
  source-dir: sources
  files:
    - source: .github/pull_request_template.md
    - source: .github/workflows/comment-on-pr.yaml
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/pre-commit-autoupdate.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .clang-format
    - source: .markdownlint.yaml
    - source: .pre-commit-config.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: CODE_OF_CONDUCT.md
    - source: CONTRIBUTING.md
    - source: CPPLINT.cfg
    - source: DISCLAIMER.md
    - source: LICENSE
