- name: Ensure apt cache is updated
  apt:
    update_cache: yes
  become: yes

- name: Install ncdu
  apt:
    name: ncdu
    state: present
  become: yes

- name: Install screenfetch
  apt:
    name: screenfetch
    state: present
  become: yes