- name: Ensure apt cache is updated
  apt:
    update_cache: true
  become: true

- name: Install ncdu
  apt:
    name: ncdu
    state: present
  become: true

- name: Install screenfetch
  apt:
    name: screenfetch
    state: present
  become: true

- name: Install ranger
  apt:
    name: ranger
    state: present
  become: true
