- name: Create directory for runner scripts
  file:
    path: /opt/runner-scripts
    state: directory
    mode: '0755'
    become: true

- name: Install the cleanup script
  copy:
    src: "{{ role_path }}/files/cleanup_script.sh"
    dest: "/opt/runner-scripts/cleanup_script.sh"
    mode: '0755'
    become: true

- name: Append cleanup script to actions-runner .env
  lineinfile:
    path: /opt/actions-runner/.env
    line: "ACTIONS_RUNNER_HOOK_JOB_STARTED=/opt/runner-scripts/cleanup_script.sh"
    create: true
    become: true
