- name: Install GitHub Actions Runner
  hosts: localhost
  runner_user: "ubuntu"
  become: yes
  vars:
    - github_account: "xmfcx"
    - github_owner: "autowarefoundation"
    - runner_org: yes
    - runner_group: "Default"
    - runner_labels: [self-hosted, Linux, X64]
  roles:
    - role: monolithprojects.github_actions_runner
