- name: Install GitHub Actions Runner
  hosts: localhost
  become: true
  vars:
    github_owner: autowarefoundation
    runner_user: ubuntu
    runner_org: true
    runner_group: Default
    runner_labels: [self-hosted, Linux, X64]
  roles:
    - role: monolithprojects.github_actions_runner
